#!/bin/bash
# PID 1 of the browser child.
#
# Four processes, started in an order that is a dependency order and not a guess:
# an X server nobody can see, a sound card that does not exist, a browser, and the
# thing that turns the first three into an H.264 stream. Each wait below is for a
# fact -- a socket answering, a sink existing -- because the node reports an
# instance ready when the guest's IP answers, which is seconds before anything in
# here has bound anything.
set -euo pipefail

log() { printf '%s [browser] %s\n' "$(date -u +%H:%M:%S)" "$*"; }
fail() { log "FATAL: $*"; exit 1; }

START_URL="${START_URL:-about:blank}"
WIDTH="${WIDTH:-1920}"
HEIGHT="${HEIGHT:-1080}"
FPS="${FPS:-30}"
SW_PRESET="${SW_PRESET:-ultrafast}"
ADMIN_USER="${ADMIN_USER:-}"
ADMIN_PASS="${ADMIN_PASS:-}"
LOCALE="${LOCALE:-en-US}"
TIMEZONE="${TIMEZONE:-UTC}"

[ -n "$ADMIN_USER" ] && [ -n "$ADMIN_PASS" ] || fail \
  "ADMIN_USER and ADMIN_PASS are unset. They are generated by the parent and passed
   in Configuration.environment_variables; empty ones would leave Sunshine's API
   open to anything that can reach port 47990, which on this node is every other
   guest on the bridge."

export DISPLAY=:0
export TZ="$TIMEZONE"
STATE=/var/lib/browser
LOGS=/var/log/browser
mkdir -p "$STATE" "$LOGS" /run/pulse
chown -R browser:browser "$STATE" /run/pulse

# --- Input: the one thing this image cannot provide for itself -----------------
#
# Sunshine injects mouse and keyboard through /dev/uinput. Nodo's guest kernel is
# built with `# CONFIG_INPUT is not set` -- switched off, per its own comment,
# because "no terminal, keyboard or physical NIC" exists in a microVM, which is
# true of hardware and not of uinput. So the node has to be asked for it; see
# NODE-REQUIREMENTS.md.
#
# This is a warning and not a fatal error on purpose. A stream you can watch and
# not touch is a degraded service, worth running and worth saying so about; a
# service that refuses to start would report the same condition as a crash.
if [ -c /dev/uinput ]; then
  log "input: /dev/uinput present -- keyboard and mouse will work"
else
  log "input: NO /dev/uinput. This stream is VIEW-ONLY: Sunshine has nothing to"
  log "input: inject through, so Moonlight's keyboard and mouse will go nowhere."
  log "input: the guest kernel needs CONFIG_INPUT=y + CONFIG_INPUT_UINPUT=y."
fi

# --- X ------------------------------------------------------------------------
#
# -ac disables X access control. Inside a microVM whose only network device is one
# tap, the set of processes that can reach this display is the set of processes in
# this image, and an xauth cookie shared between two of them proves nothing to
# either. The boundary here is the VM, not MIT-MAGIC-COOKIE-1.
log "starting Xvfb at ${WIDTH}x${HEIGHT}x24"
Xvfb :0 -screen 0 "${WIDTH}x${HEIGHT}x24" -ac -nolisten tcp -noreset \
  >"$LOGS/xvfb.log" 2>&1 &
XVFB_PID=$!

for _ in $(seq 1 100); do
  xdpyinfo -display :0 >/dev/null 2>&1 && break
  sleep 0.1
done
xdpyinfo -display :0 >/dev/null 2>&1 || fail "Xvfb never answered on :0 (see $LOGS/xvfb.log)"
log "X display :0 is up"

# --- Audio --------------------------------------------------------------------
#
# The guest kernel has `# CONFIG_SOUND is not set`, so there is no ALSA device and
# nothing to open. module-null-sink does not want one: it is arithmetic on a
# buffer, and its monitor source is a real capture source as far as Sunshine is
# concerned. Audio is the only capability in this service that needs nothing at
# all from the node.
cat > /etc/pulse/nodo.pa <<'PA'
load-module module-native-protocol-unix auth-anonymous=1 socket=/run/pulse/native
load-module module-null-sink sink_name=nodo_null sink_properties=device.description=nodo-null
set-default-sink nodo_null
PA
log "starting pulseaudio with a null sink"
pulseaudio --system --disallow-exit --exit-idle-time=-1 -n --file=/etc/pulse/nodo.pa \
  >"$LOGS/pulse.log" 2>&1 &
PULSE_PID=$!

for _ in $(seq 1 100); do
  [ -S /run/pulse/native ] && break
  sleep 0.1
done
[ -S /run/pulse/native ] || log "WARNING: pulseaudio socket never appeared; the stream will be silent"
export PULSE_SERVER=unix:/run/pulse/native

# --- Sunshine -----------------------------------------------------------------
#
# capture = x11 is not a preference. Sunshine's Wayland capture is built on
# wlr-export-dmabuf, and a dmabuf needs a DRM device; the guest kernel has
# `# CONFIG_DRM is not set`, so there is no /dev/dri to export from and the kms
# path is gone for the same reason. X11's capture is XShm -- ordinary shared
# memory, no device -- which is what makes it the only one of the three that can
# run on this kernel. Wayland is still the right answer at the *other* end of the
# chain, where isolation is the question; see NODE-REQUIREMENTS.md.
#
# encoder = software for the same kind of reason, one layer up: celaut.Sysresources
# is mem_limit, disk_space, cpu_period, cpu_quota and blkio_weight, with no field
# for an accelerator. A service cannot ask a node for one, so an encoder that needs
# one cannot be scheduled anywhere on this network.
cat > /etc/sunshine/sunshine.conf <<CONF
port = 47989
address_family = ipv4
upnp = off
origin_web_ui_allowed = wan
capture = x11
encoder = software
sw_preset = ${SW_PRESET}
sw_tune = zerolatency
audio_sink = nodo_null.monitor
min_log_level = info
log_path = ${LOGS}/sunshine.log
credentials_file = ${STATE}/sunshine_creds.json
file_state = ${STATE}/sunshine_state.json
file_apps = ${STATE}/apps.json
fps = [${FPS}]
resolutions = [${WIDTH}x${HEIGHT}]
CONF

# One app, and it is the desktop: an entry with no `cmd` streams the X display as
# it is. The browser is already running on it, and Moonlight launching a second
# copy of anything is not a thing this service wants to be able to do.
cat > "$STATE/apps.json" <<APPS
{
  "env": {},
  "apps": [
    { "name": "Browser" }
  ]
}
APPS

log "seeding Sunshine credentials for user '${ADMIN_USER}'"
sunshine /etc/sunshine/sunshine.conf --creds "$ADMIN_USER" "$ADMIN_PASS" \
  >"$LOGS/creds.log" 2>&1 || fail "sunshine --creds failed (see $LOGS/creds.log)"

log "starting sunshine (encoder=software preset=${SW_PRESET} ${WIDTH}x${HEIGHT}@${FPS})"
sunshine /etc/sunshine/sunshine.conf >"$LOGS/sunshine.stdout" 2>&1 &
SUNSHINE_PID=$!

# --- Chromium -----------------------------------------------------------------
#
# --disable-gpu, and then software rasterisation is what is left. There is no
# /dev/dri to fall back from, so this flag is a description of the machine rather
# than a choice: pages of text are fine, and anything that expects a compositor to
# do its work -- WebGL, video at full frame rate -- is where the cost of a browser
# with no GPU actually shows.
#
# runuser drops to an unprivileged user so Chromium keeps its own sandbox. See the
# Dockerfile: the guest kernel has the namespaces and seccomp it needs, and this is
# the one service on the network whose job is to open pages nobody vetted.
log "starting chromium at ${START_URL}"
runuser -u browser -- \
  chromium \
    --kiosk \
    --no-first-run \
    --no-default-browser-check \
    --disable-gpu \
    --disable-dev-shm-usage \
    --window-size="${WIDTH},${HEIGHT}" \
    --window-position=0,0 \
    --lang="${LOCALE}" \
    --user-data-dir="${STATE}/profile" \
    --disk-cache-dir="${STATE}/cache" \
    "${START_URL}" \
  >"$LOGS/chromium.log" 2>&1 &
CHROMIUM_PID=$!

log "up: xvfb=${XVFB_PID} pulse=${PULSE_PID} sunshine=${SUNSHINE_PID} chromium=${CHROMIUM_PID}"

# PID 1 exits when any of the four does. None of them is optional: without X there
# is nothing to capture, without Sunshine nothing to connect to, and a browser that
# died leaves a stream of a blank screen that looks exactly like a working service.
# The node notices the instance is gone; a half-dead one it would not notice at all.
wait -n
log "a child process exited; shutting the instance down"
kill "$XVFB_PID" "$PULSE_PID" "$SUNSHINE_PID" "$CHROMIUM_PID" 2>/dev/null || true
exit 1
